// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtro1zvVcS1c-klsDLjlwFU1eU6tPDRR0',
    appId: '1:600559423345:web:dfb7db288040966e5c30d0',
    messagingSenderId: '600559423345',
    projectId: 'splitter-2e1ae',
    authDomain: 'splitter-2e1ae.firebaseapp.com',
    storageBucket: 'splitter-2e1ae.firebasestorage.app',
    measurementId: 'G-SN6YX56GQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLDERY7VuNSO6yDbtInKQ_YfDg2IiZ84o',
    appId: '1:600559423345:android:922589b03c7cf8bd5c30d0',
    messagingSenderId: '600559423345',
    projectId: 'splitter-2e1ae',
    storageBucket: 'splitter-2e1ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZDU8LLxS-_ES5lF8NTkrzbYpqzq2Yso',
    appId: '1:600559423345:ios:33be11ce12bd86385c30d0',
    messagingSenderId: '600559423345',
    projectId: 'splitter-2e1ae',
    storageBucket: 'splitter-2e1ae.firebasestorage.app',
    androidClientId: '600559423345-t4ap058lhavrjeq5dn0k2ms8mj49gum9.apps.googleusercontent.com',
    iosClientId: '600559423345-2b5t27f6pejto8ci75r0k65o46ch4o2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeZDU8LLxS-_ES5lF8NTkrzbYpqzq2Yso',
    appId: '1:600559423345:ios:33be11ce12bd86385c30d0',
    messagingSenderId: '600559423345',
    projectId: 'splitter-2e1ae',
    storageBucket: 'splitter-2e1ae.firebasestorage.app',
    androidClientId: '600559423345-t4ap058lhavrjeq5dn0k2ms8mj49gum9.apps.googleusercontent.com',
    iosClientId: '600559423345-2b5t27f6pejto8ci75r0k65o46ch4o2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtro1zvVcS1c-klsDLjlwFU1eU6tPDRR0',
    appId: '1:600559423345:web:fdf7d1a3283834ac5c30d0',
    messagingSenderId: '600559423345',
    projectId: 'splitter-2e1ae',
    authDomain: 'splitter-2e1ae.firebaseapp.com',
    storageBucket: 'splitter-2e1ae.firebasestorage.app',
    measurementId: 'G-PJ6REFB9Q7',
  );

}